# __________________________________________________________
# //////////////////////////////////////////////////////////
#
#    DATA PREPARATION
# __________________________________________________________
# //////////////////////////////////////////////////////////

rm(list=ls(all=TRUE))
setwd("~/Documents/github/2015CMA/RFM")
setwd("~/OneDrive/B_Data/Berner_PT")

# Load necessary libraries
library(DBI)
library(RSQLite)
library(proto)
library(gsubfn)
library(tcltk)

# Compute key marketing indicators using SQL language
library(sqldf)

# Load text file into local variable called 'raw data'
raw_data_1 = read.delim(file = 'Customer_purchases_2011_2013_with_empty_amounts.csv', header = FALSE, sep = ',', dec = '.')
raw_data_2 = read.delim(file = 'purchases_2014.txt', header = FALSE, sep = ',', dec = '.')
raw_data_3 = read.delim(file = 'purchases_2015-10-19.txt', header = FALSE, sep = ',', dec = '.')
raw_data_4 = merge(raw_data_1, raw_data_2, all.x = TRUE, all.y = TRUE)
raw_data_5 = merge(raw_data_4, raw_data_3, all.x = TRUE, all.y = TRUE)

# Remove raw data from memory
rm(raw_data_1, raw_data_2, raw_data_3, raw_data_4)

# Add headers and interpret the last column as a date, extract year of purchase
# Set the starting date for calculating days since the last purchase was done
colnames(raw_data_5) = c('customer_id', 'purchase_amount', 'date_of_purchase')
raw_data_5$date_of_purchase = as.Date(raw_data_5$date_of_purchase, "%Y-%m-%d")
raw_data_5$year_of_purchase = as.numeric(format(raw_data_5$date_of_purchase, "%Y"))

# Set date for calculation of difftime
raw_data_5$days_since       = as.numeric(difftime(time1 = "2016-01-01", time2 = raw_data_5$date_of_purchase, units = "days"))

# Data cleansing of customers without purchases in this file
raw_data_6 = na.omit(raw_data_5)
# Remove transactions (credit note) with negative amount
# data = sqldf("SELECT * FROM raw_data_6 WHERE purchase_amount > 0")

# Remove data from memory 
rm(raw_data_5)

# --------------- Data Cleansing, Filter out all puchases with following returns -------------------------------
#

# Select all customer transactions in the selected period 
#purchases = sqldf("SELECT * FROM data WHERE purchase_amount > 0")

# Select all customer without any transactions in the selected period
#credits = sqldf("SELECT * FROM data WHERE purchase_amount < 0")

# Delete purchases with following returns
#new_data = purchases[ !(purchases$customer_id %in% bookback$customer_id), ]
# Filtering out Customers with order and following return
#customers_with_order_and_return = sqldf("DELETE * FROM purchases INNER JOIN credits ON purchases.customer_id = credits.customer_id WHERE -credits.purchase_amount = purchases.purchase_amount")
#clean = merge(purchases, credits, by="customer_id", all.y=TRUE)

#rm(purchases, credits)

# Assignment of purchase amount and date of purchase to customers without transactions
#customers_without_transactions$V3 = "2000-01-01"
#customers_without_transactions$V2 = "0.00"

# Select all customers with negative purchase in the selected period
# negative_data = sqldf("SELECT * FROM raw_data WHERE V2 < 0")

# Merge the processed data together in one object
#data = merge(customers_with_transactions, customers_without_transactions, all.x = TRUE, all.y = TRUE)

# 
# Filtering out all transactions with a negative amount of purchase
# Non Consideration of Orders with following Returns
#

#customers_with_purchases = sqldf("SELECT * FROM raw_data WHERE V2 > -0.01")
#data = sqldf("SELECT * FROM data WHERE V2 > 0.00")
#data = sqldf("SELECT * FROM raw_data WHERE V2 > -0.01 AND V3 NOT LIKE 0")

# --- COMPUTING RECENCY, FREQUENCY, MONETARY VALUE ---------

# --- Call the rfm segmentation function and return the processed df ------------------

# Customers with purchase in 2015
customers_2015 <- rfmSegmentation(data, 150, 0)
# Customers with purchase in 2014
customers_2014 <- rfmSegmentation(data, 150, 365)
# Customers with purchase in 2012
customers_2013 <- rfmSegmentation(data, 150, 730)
# Customers with purchase in 2011
customers_2012 <- rfmSegmentation(data, 150, 1095)

# --- COMPUTING REVENUE GENERATION PER SEGMENT -------------

# Compute how much revenue is generated by segments
# Notice that people with no revenue in 2015 do NOT appear
revenue_2015 = sqldf("SELECT customer_id, SUM(purchase_amount) AS 'revenue_2015'
                     FROM data
                     WHERE year_of_purchase = 2015
                     GROUP BY 1")
summary(revenue_2015)

revenue_2014 = sqldf("SELECT customer_id, SUM(purchase_amount) AS 'revenue_2014'
                     FROM data
                     WHERE year_of_purchase = 2014
                     GROUP BY 1")
summary(revenue_2014)

# --- DEVELOP A PREDICTIVE MODEL --- 

# --- CREATE ENHANCED CUSTOMER DATA SET WITH MAX. AND AVG. PURCHASE AMOUNT -------------
# 
# Compute RFM variables as of a year ago (Enhanced)
enhanced_customers_2014 = sqldf("SELECT customer_id,
                                MIN(days_since) - 365 AS 'recency',
                                MAX(days_since) - 365 AS 'first_purchase',
                                COUNT(*) AS 'frequency',
                                AVG(purchase_amount) AS 'avg_amount',
                                MAX(purchase_amount) AS 'max_amount'
                                FROM data
                                WHERE days_since > 365
                                GROUP BY 1")
